# Generated by Django 5.1.3 on 2024-11-22 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classroomApp", "0003_alter_room_options_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
