# Generated by Django 5.1.3 on 2024-12-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroomApp", "0005_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, default=None, upload_to="avatars/"),
        ),
    ]
