# Generated by Django 5.1.3 on 2025-03-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroomApp", "0006_alter_message_body_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, upload_to="static/media/avatars/"
            ),
        ),
    ]
