# Generated by Django 5.1.3 on 2025-03-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroomApp", "0007_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, default=None, upload_to="avatars/"),
        ),
    ]
